apiVersion: v1
kind: Service
metadata:
  name: sample-service
spec:
  type: NodePort
  selector:
    app: my-dryrun-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 32123