# nginx-config.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Simple 2-Tier Web App</title>
    </head>
    <body>
      <h1>Welcome to the Front-End!</h1>
      <p>This is a simple 2-tier application with Kubernetes.</p>
    </body>
    </html>
