# node-api-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
        - name: node-api
          image: node:14
          command: ["node", "/app/server.js"]
          volumeMounts:
            - name: app-volume
              mountPath: /app
          ports:
            - containerPort: 3000
      volumes:
        - name: app-volume
          configMap:
            name: node-api-config
---
apiVersion: v1
kind: Service
metadata:
  name: node-api
spec:
  selector:
    app: node-api
  ports:
    - port: 3000
      targetPort: 3000
