apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: ngApp
ports:
  - name: http
    port: 80 #Service port
    targetPort: 80 #container port
    nodePort: 32123